"""Add permission history table

Revision ID: def456789abc
Revises: abc123456789
Create Date: 2025-06-19 14:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'def456789abc'
down_revision = 'abc123456789'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission_history',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('previous_level', sa.Enum('READ', 'WRITE', 'ADMIN', name='permissionlevel'), nullable=True),
        sa.Column('new_level', sa.Enum('READ', 'WRITE', 'ADMIN', name='permissionlevel'), nullable=False),
        sa.Column('changed_by', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('reason', sa.String(length=500), nullable=False),
        sa.Column('okta_groups_before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('okta_groups_after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('source', sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(['changed_by'], ['user.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_permission_history_changed_at', 'permission_history', ['changed_at'])
    op.create_index('ix_permission_history_user_id', 'permission_history', ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_permission_history_user_id', table_name='permission_history')
    op.drop_index('ix_permission_history_changed_at', table_name='permission_history')
    op.drop_table('permission_history')
    # ### end Alembic commands ###
